spring:
  datasource:
    name: test
    url: jdbc:mysql://106.12.128.96:3306/miniprogram?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    #url: jdbc:mysql://localhost:3306/miniprogram?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#server:
#  port: 443
#  ssl:
#    key-store: SHA256withRSA_www.rachal.top.pfx
#    key-store-password: 7894
#    key-store-type: PKCS12

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.homestay.entity
  configuration:
    map-underscore-to-camel-case: true